export const GET_ERRORS = 'GET_ERRORS'; 

// Tasks
export const TASKS_LOADING = 'TASKS_LOADING';
export const GET_TASKS = 'GET_TASKS';
export const GET_COMPLETED_TASK = 'GET_COMPLETED_TASK';
export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';

// WebSockets
export const WEBSOCKET_CONNECT = "WEBSOCKET_CONNECT";
export const WEBSOCKET_CONNECTING = "WEBSOCKET_CONNECTING";
export const WEBSOCKET_CONNECTED = "WEBSOCKET_CONNECTED";
export const WEBSOCKET_DISCONNECT = "WEBSOCKET_DISCONNECT";
export const WEBSOCKET_DISCONNECTED = "WEBSOCKET_DISCONNECTED";
export const WEBSOCKET_MESSAGE = "WEBSOCKET_MESSAGE";