export const GET_ERRORS = 'GET_ERRORS'; 

// Tasks
export const TASKS_LOADING = 'TASKS_LOADING';
export const GET_TASKS = 'GET_TASKS';
export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';

// WebSockets
export const WEBSOCKET_CONNECT = "WS_CONNECT";
export const WEBSOCKET_CONNECTING = "WS_CONNECTING";
export const WEBSOCKET_CONNECTED = "WS_CONNECTED";
export const WEBSOCKET_DISCONNECT = "WS_DISCONNECT";
export const WEBSOCKET_DISCONNECTED = "WS_DISCONNECTED";
export const WEBSOCKET_MESSAGE = "WS_MESSAGE";